apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "Stephan-nodejs"
  annotations:
    "humanitec.com/orgId": "htc-demo-03"
    "humanitec.com/appId": "Stephan-nodejs"
spec:
  type: service
  owner: user:guest
  lifecycle: experimental
